# Generated by Django 4.1.5 on 2023-02-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystaff',
            name='role',
            field=models.CharField(blank=True, choices=[('SALES', 'Sales'), ('MANAGER', 'Manager'), ('CHEF', 'Chef'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterModelTable(
            name='mystaff',
            table='mystaff',
        ),
    ]
