# Generated by Django 4.1.5 on 2023-02-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_mystaff_role_alter_mystaff_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystaff',
            name='join_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
