# Generated by Django 4.1.5 on 2023-02-10 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_mystaff_role_alter_mystaff_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mystaff',
            name='join_date',
            field=models.DateField(default=datetime.date(2023, 2, 10)),
        ),
    ]
