# Generated by Django 4.1.5 on 2023-05-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_myuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mystaff',
            old_name='staff',
            new_name='user',
        ),
    ]
