# Generated by Django 4.1.5 on 2023-02-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant_app', '0002_alter_menuinventory_id_alter_ordermenu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
