# Generated by Django 4.1.5 on 2023-02-25 23:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant_app', '0003_alter_inventory_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.AlterField(
            model_name='menuinventory',
            name='units',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0, message='unit is not a positive')]),
        ),
    ]
