# Generated by Django 4.1.5 on 2023-04-07 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant_app', '0004_delete_dashboard_alter_menuinventory_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuinventory',
            name='inventory_id',
            field=models.ForeignKey(db_column='inventory_id', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='myrestaurant_app.inventory'),
        ),
        migrations.AlterField(
            model_name='menuinventory',
            name='menu_id',
            field=models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, related_name='units', to='myrestaurant_app.menu'),
        ),
    ]
