# Generated by Django 4.1.5 on 2023-04-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant_app', '0008_alter_menuinventory_inventory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='in_stock',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
