# Generated by Django 4.1.5 on 2023-05-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant_app', '0012_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='ingredient',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
