# Generated by Django 4.1.5 on 2023-05-25 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant_app', '0013_alter_inventory_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='in_stock',
        ),
        migrations.AlterField(
            model_name='menu',
            name='available_quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0, message='unit is not a positive')]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ingredients_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
