# Generated by Django 4.1.5 on 2023-06-12 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant_app', '0015_alter_inventory_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='available_quantity',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='Unit is not a positive')]),
        ),
    ]
