# Generated by Django 4.1.5 on 2023-02-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('ingredient', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=30, null=True, unique=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, upload_to='inventory')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=30, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Menu',
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_items', models.CharField(max_length=300)),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('prepared', models.BooleanField(default=False)),
                ('prepared_at', models.DateTimeField(default=None, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(default=None, null=True)),
                ('complete', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
    ]
