# Generated by Django 4.1.5 on 2023-02-15 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_statistics', models.JSONField(default=dict, null=True)),
                ('inventory_statistics', models.JSONField(default=dict, null=True)),
                ('menu_statistics', models.JSONField(default=dict, null=True)),
            ],
            options={
                'db_table': 'dashboard',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ingredient', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30, unique=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5)),
                ('image', models.ImageField(blank=True, upload_to='inventory')),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=30, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu')),
                ('description', models.TextField(blank=True)),
                ('ingredients_cost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, max_length=300, null=True)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('prepared', models.BooleanField(default=False)),
                ('prepared_at', models.DateTimeField(default=None, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('delivered_at', models.DateTimeField(default=None, null=True)),
                ('complete', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(null=True)),
                ('menu_id', models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders_menu', to='myrestaurant_app.menu')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='orders_menu', to='myrestaurant_app.order')),
            ],
            options={
                'db_table': 'orders_menu',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='menu_items',
            field=models.ManyToManyField(through='myrestaurant_app.OrderMenu', to='myrestaurant_app.menu'),
        ),
        migrations.CreateModel(
            name='MenuInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('inventory_id', models.ForeignKey(db_column='inventory_id', on_delete=django.db.models.deletion.CASCADE, related_name='menu_inventory', to='myrestaurant_app.inventory')),
                ('menu_id', models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, related_name='menu_inventory', to='myrestaurant_app.menu')),
            ],
            options={
                'db_table': 'menu_inventory',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='ingredients',
            field=models.ManyToManyField(through='myrestaurant_app.MenuInventory', to='myrestaurant_app.inventory'),
        ),
    ]
