# Generated by Django 4.1.5 on 2023-02-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuinventory',
            name='inventory_id',
            field=models.ForeignKey(db_column='inventory_id', on_delete=django.db.models.deletion.CASCADE, to='myrestaurant_app.inventory'),
        ),
        migrations.AlterField(
            model_name='menuinventory',
            name='menu_id',
            field=models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, to='myrestaurant_app.menu'),
        ),
        migrations.AlterField(
            model_name='menuinventory',
            name='units',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
