# Generated by Django 4.1.5 on 2023-02-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='inventory_statistics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='menu_statistics',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='order_statistics',
            field=models.JSONField(default=dict),
        ),
    ]
