# Generated by Django 4.1.5 on 2023-02-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuinventory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordermenu',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
