# Generated by Django 4.1.5 on 2023-02-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant_app', '0002_alter_menuinventory_inventory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuinventory',
            name='inventory_id',
            field=models.ForeignKey(db_column='inventory_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='myrestaurant_app.inventory'),
        ),
        migrations.AlterField(
            model_name='menuinventory',
            name='menu_id',
            field=models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='myrestaurant_app.menu'),
        ),
    ]
