# Generated by Django 4.1.5 on 2023-02-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant_app', '0003_alter_menuinventory_inventory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', through='myrestaurant_app.MenuInventory', to='myrestaurant_app.inventory'),
        ),
    ]
