# Generated by Django 4.1.5 on 2023-02-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant_app', '0004_alter_menu_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ingredients_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5),
        ),
    ]
