# Generated by Django 4.1.5 on 2023-04-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant_app', '0009_menu_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='in_stock',
            field=models.BooleanField(),
        ),
    ]
