# Generated by Django 4.1.5 on 2023-04-16 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant_app', '0010_alter_menu_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='available_quantity',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='unit is not a positive')]),
        ),
    ]
